// <auto-generated />
namespace CursoAspMvcConAutenticacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TituloRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TituloRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202004130040221_Titulo Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
